#index:
#    path: /
#    controller: App\Controller\DefaultController::index


#homepage:
#    path: /{_locale}
#    controller: App\Controller\BlogController:homepage
#    defaults: {_locale: en}
#    requirements:
#        _locale: en|fr

#blog_list:
#    path: /blog/{page}
#    controller: App\Controller\BlogController:list
#    defaults: {page: 1}
#    requirements:
#        page: '\d+'

#blog_show:
#    path: /blog/{slug}
#    controller: App\Controller\BlogController:show

